### ISSUE TITLE
Key field can't be of 'Byte[]' type

### ISSUE THREAD

**Issue by matthewhancock** [DataObjects-NET/dataobjects-net#129]
Hi, I was prototyping with an Entity that has a `byte[]` (converted `Ulid`) as a key. Would it be possible to narrow this filter to allow `byte[]` as a key, or are there other reasons for the limitation?

https://github.com/DataObjects-NET/dataobjects-net/blob/1ca7dfc9a6fb8a996f5b7ed83ebc5680ed6e706a/Orm/Xtensive.Orm/Orm/Building/Validator.cs#L132

Thanks!

**Comment by alex-kulakov** [comment]
Hello Matthew,

From what I know and see I can assume it was made to generalize primary key types across supported RDBMS. (Maybe there is some reasons I don't know yet.)

Some of the supported RDBMS do not allow native equivalent of ```byte[]``` to be part of primary key. Because of that I cannot remove this check completely.

I have found that ULID is compatible with UUID [(here)](https://github.com/ulid/spec). So it is compatible with GUID. If it is then have you tried to create a GUID value from it? Any problems with this I don't know about?

**Comment by matthewhancock** [comment]
The bit ordering and comparison between Guids and binary(16) in SQL server appears to be slightly different: https://github.com/rmalayter/ulid-mssql

> SQL Server sorts UUIDs in an unexpected way; the last 48 bits are sorted first as a big-endian binary unit, followed by other components bits as little-endian chunks.

The first 6 bytes in Ulids are the most critical as they are they are an encoded timestamp which maintains the chronology (the last 10 bytes are random).

I haven't played around enough to know how big an issue it is, but am just a little wary of mapping the two types together because they contain the same amount of bytes. It may also lead to unintentional use or reliance on Guid functionality (e.g. newid()) that would undermine some of the benefits of Ulids.


Also, sorry this is slightly unrelated, it would need to be a byte[] or Guid defined as a field (and not Ulid) because DO doesn't have value converter functionality, like Entity Framework, where you can globally specify a type to how it should be handled by the database, right?

**Comment by alex-kulakov** [comment]
Thank you for the link to performance tests. ULIDs seem to perform better than UUIDs

> Also, sorry this is slightly unrelated, it would need to be a byte[] or Guid defined as a field (and not Ulid) because DO doesn't have value converter functionality, like Entity Framework, where you can globally specify a type to how it should be handled by the database, right?

If it is about my suggestion then I meant to have ```Guid``` Field but the values for it should be manually created by using ```byte[]``` containing ulid data. But in context of bad sort behavior in MS SQL Server it is not an option.

DO has no such converters functionality. Type mappings (.Net type to storage native type and vice versa) are defined within drivers. Each driver "knows" type set it supports (```Validator.cs``` has the ```supportedTypes``` collection, these types are from the driver), it also "knows" how to map values of known types to parameters and how to read them from query results.

How critical is it for you to have such Primary Keys?

**Comment by matthewhancock** [comment]
Thanks for the info, there's no criticality at the moment, really just in the prototyping stage. I think the direction is towards a hybrid approach with document databases and Ulids solving some of the clustering issues of Guids would make it a good unified type to serve as IDs between the two database types. So eventually it will be necessary as a primary key.
