### ISSUE TITLE
Bulk update with Contains throws NullReferenceException

### ISSUE THREAD

**Issue by commit-n-run** [DataObjects-NET/dataobjects-net#20]
Model part is not important here, example code:

```cs
[SetUp]
public void SetUp()
{
    tagIds = Enumerable.Range(0, 100).Select(i => (long)i);
}

[Test]
public void Test1()
{
    Session.Query.All<TagType>()
        .Where(t => t.Id.In(tagIds))
        .Set(t => t.ProjectedValueAdjustment, 0)
        .Update();
}

[Test]
public void Test2()
{

    Session.Query.All<TagType>()
        .Where(t => t.Id.In(IncludeAlgorithm.ComplexCondition, tagIds))
        .Set(t => t.ProjectedValueAdjustment, 0)
        .Update();
}

[Test]
public void Test3()
{
    Session.Query.All<TagType>()
        .Where(t => t.Id.In(IncludeAlgorithm.TemporaryTable, tagIds))
        .Set(t => t.ProjectedValueAdjustment, 0)
        .Update();
}

[Test]
public void Test4()
{
    Session.Query.All<TagType>()
        .Where(t => tagIds.Contains(t.Id))
        .Set(t => t.ProjectedValueAdjustment, 0)
        .Update();
}

```

Test1 - executes fine
Test2 - executes fine
Test3 - throws `NotSupportedException`, which is also fine
Test3 - throws `NullReferenceException`

It seems that internally query in `Test1` is [rewritten](https://github.com/DataObjects-NET/dataobjects-net/blob/master/Extensions/Xtensive.Orm.BulkOperations/Internals/QueryOperation.cs#L40) to be like query in `Test2` and query in `Test3` is explicitly disallowed.

DO LINQ translator usually handles `Contains` the same way as `In` without `IncludeAlgorithm`.

I think `QueryOperation` should do the same, e.g. rewrite `foo.Contains(bar)` as `bar.In(IncludeAlgorithm.ComplexCondition, foo)`

**Comment by alex-kulakov** [comment]
Yes, I agree with that.
