### ISSUE TITLE
FullText - Azure SQL Server - Issue on building domain, extracted schema differs from targeted schema

### ISSUE THREAD

**Issue by rlesavre** [DataObjects-NET/dataobjects-net#205]
When using a Fulltext index on the model using an Azure SQL server on azure, the initial domain creation works, and the full text index is working however, on next domain building, DO seems to be unable to see the Index, and detect a domain change:

![image](https://user-images.githubusercontent.com/5682585/145376990-cc3b2a9a-da2d-4b48-9563-7f20eabded3b.png)
![image](https://user-images.githubusercontent.com/5682585/145377083-89731420-0d90-4f10-a66a-f8e62ff83b32.png)

Schema comparison result: TargetIsSuperset
Has unsafe actions: false
Has column type changes: false 
Compatible in ValidateLegacy mode: unknown

Unsafe actions:

Schema hints:
  
Schema difference:
  "./" != "./" (NodeDifference): Unknown
    +Tables: "./Tables (7)" != "./Tables (7)" (NodeCollectionDifference): 1 change(s)
      "./Tables/Book" != "./Tables/Book" (NodeDifference): Unknown
        +FullTextIndexes: "./Tables/Book/FullTextIndexes (0)" != "./Tables/Book/FullTextIndexes (1)" (NodeCollectionDifference): 1 change(s)
          "" != "./Tables/Book/FullTextIndexes/FT_Book" (NodeDifference): Created
            +Columns: "" != "./Tables/Book/FullTextIndexes/FT_Book/Columns (1)" (NodeCollectionDifference): 1 change(s)
              "" != "./Tables/Book/FullTextIndexes/FT_Book/Columns/0" (NodeDifference): Created
                +Configuration: "" != "French" (ValueDifference): values differ
                +Value: "" != "./Tables/Book/Columns/Title" (ValueDifference): values differ

This exact same code works on an hosted SQL Server instance, is there is an issue with the extracted Schema ?

**Comment by alex-kulakov** [comment]
Hello @rlesavre,

I don't know such issues yet. Also the DO version is important here, could you specify it? I'll check the case.

**Comment by rlesavre** [comment]
Thanks @alex-kulakov i'm having the same behavior with the 7.0.1 or 6.0.6.

**Comment by alex-kulakov** [comment]
I confirm this problem. I'll fix it in next releases.
