### ISSUE TITLE
Do not activate session in EntitySet enumerator

### ISSUE THREAD

**Issue by letarak** [DataObjects-NET/dataobjects-net#284]
We try live without session activation (custom resolver logic) and this issue mess things up

    public static IEnumerable<T> ToTransactional<T>(this IEnumerable<T> source, Session session, IsolationLevel isolationLevel)
    {
      using (session.Activate(true))
      using (var tx = session.OpenAutoTransaction(isolationLevel)) {
        foreach (var item in source)
          yield return item;
        tx.Complete();
      }
    }

**Comment by alex-kulakov** [comment]
I need to check it first, but it sounds reasonable to not activate session. I'm not sure whether it will be ok when there are two sessions s1 and s2 and s1 is activated but ```ToTransactional``` happens in an EntitySet which belongs to s2.
