### ISSUE TITLE
Move SQL server provider to separate package

### ISSUE THREAD

**Issue by commit-n-run** [DataObjects-NET/dataobjects-net#3]
`System.Data.SqlClient` is no longer a part of standard class library.
It's a separate NuGet package like all other ADO.NET providers.
I think there is no need to handle it specially now.

**Comment by alex-kulakov** [comment]
Thank you for your suggestion, I agree and have moved MS SQL Server provider to separate project. Used the same package that was in the Xtensive.Orm project for now.

**Comment by commit-n-run** [comment]
Pretty cool, thank you
